### PR TITLE
Init en-US version & update some translates

### PR DESCRIPTION
**Pull request by beautifultable**

### CODE REVIEW

**Comment by medz** [comment]
Thanks

Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2017年4月10日，21:02，beautifultable <notifications@github.com<mailto:notifications@github.com>> 写道：

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/medz/phpwind-docs/pull/1

Commit Summary

  *   Init en-US version & update some translates

File Changes

  *   A assets/v1.0/en-US/2017-dev.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-0> (46)
  *   A assets/v1.0/en-US/contributing.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-1> (42)
  *   A assets/v1.0/en-US/get-started/phpwind9-1.0.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-2> (41)
  *   A assets/v1.0/en-US/get-started/upgrade-introduction.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-3> (3)
  *   A assets/v1.0/en-US/installed/installation.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-4> (84)
  *   A assets/v1.0/en-US/introduction.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-5> (11)
  *   A assets/v1.0/en-US/releases.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-6> (18)
  *   A assets/v1.0/en-US/summary.json<https://github.com/medz/phpwind-docs/pull/1/files#diff-7> (45)
  *   M assets/v1.0/language.json<https://github.com/medz/phpwind-docs/pull/1/files#diff-8> (3)
  *   A assets/v1.1/en-US/2017-dev.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-9> (46)
  *   A assets/v1.1/en-US/contributing.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-10> (42)
  *   A assets/v1.1/en-US/get-started/phpwind9-1.0.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-11> (41)
  *   A assets/v1.1/en-US/get-started/upgrade-introduction.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-12> (3)
  *   A assets/v1.1/en-US/installed/installation.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-13> (89)
  *   A assets/v1.1/en-US/introduction.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-14> (11)
  *   A assets/v1.1/en-US/releases.md<https://github.com/medz/phpwind-docs/pull/1/files#diff-15> (18)
  *   A assets/v1.1/en-US/summary.json<https://github.com/medz/phpwind-docs/pull/1/files#diff-16> (45)
  *   M assets/v1.1/language.json<https://github.com/medz/phpwind-docs/pull/1/files#diff-17> (3)

Patch Links:

  *   https://github.com/medz/phpwind-docs/pull/1.patch
  *   https://github.com/medz/phpwind-docs/pull/1.diff

**Comment by medz** [comment]
还有更多翻译在这个pr提交还是重新提交pr？如果继续翻译，我等你确定可以合并的时候合并你的pr。感谢。

**Comment by beautifultable** [comment]
啊哈，不太会用git。。。

**Comment by beautifultable** [comment]
1.0和1.1的内容现在是一样的吧。。。

**Comment by medz** [comment]
1.1的文档还没有怎么写～逐步晚上，我等你继续commit，翻译完了我在合并吧～

**Comment by medz** [comment]
我看了文件～差不多都翻译了，我合并了～

**Pull request merged**
